"""
Built-in workflow templates for common multi-Agent collaboration patterns.

Each template is a dict with keys: name, description, category, steps.
Steps follow the same schema as CreateWorkflowArgs.steps.
"""

WORKFLOW_TEMPLATES = [
    {
        "key": "code_review_pipeline",
        "name": "代码审查流水线",
        "description": "自动化的代码审查→测试→部署工作流。适合有独立审查和部署 Agent 的团队。",
        "category": "devops",
        "steps": [
            {
                "step_key": "code_review",
                "name": "代码审查",
                "order": 0,
                "depends_on": [],
                "required_capabilities": ["code_review"],
                "on_failure": "abort",
                "retry_count": 0,
            },
            {
                "step_key": "testing",
                "name": "自动化测试",
                "order": 1,
                "depends_on": ["code_review"],
                "required_capabilities": ["testing"],
                "on_failure": "abort",
                "retry_count": 1,
            },
            {
                "step_key": "deployment",
                "name": "部署发布",
                "order": 2,
                "depends_on": ["testing"],
                "required_capabilities": ["deployment"],
                "on_failure": "abort",
                "retry_count": 0,
            },
        ],
    },
    {
        "key": "research_and_report",
        "name": "研究与报告",
        "description": "研究 Agent 收集信息 → 协调者整理 → 文档 Agent 撰写报告。",
        "category": "research",
        "steps": [
            {
                "step_key": "research",
                "name": "信息收集与研究",
                "order": 0,
                "depends_on": [],
                "required_capabilities": ["research"],
                "on_failure": "abort",
                "retry_count": 0,
            },
            {
                "step_key": "analysis",
                "name": "分析与整理",
                "order": 1,
                "depends_on": ["research"],
                "required_capabilities": ["coordination"],
                "on_failure": "abort",
                "retry_count": 0,
            },
            {
                "step_key": "documentation",
                "name": "撰写文档报告",
                "order": 2,
                "depends_on": ["analysis"],
                "required_capabilities": ["documentation"],
                "on_failure": "continue",
                "retry_count": 0,
            },
        ],
    },
    {
        "key": "parallel_review",
        "name": "并行审查",
        "description": "安全审查与代码质量审查并行执行，完成后由协调者合并结果。",
        "category": "review",
        "steps": [
            {
                "step_key": "security_review",
                "name": "安全审查",
                "order": 0,
                "depends_on": [],
                "required_capabilities": ["security"],
                "on_failure": "continue",
                "retry_count": 0,
            },
            {
                "step_key": "quality_review",
                "name": "代码质量审查",
                "order": 1,
                "depends_on": [],
                "required_capabilities": ["code_review"],
                "on_failure": "continue",
                "retry_count": 0,
            },
            {
                "step_key": "merge_results",
                "name": "合并审查结果",
                "order": 2,
                "depends_on": ["security_review", "quality_review"],
                "required_capabilities": ["coordination"],
                "on_failure": "abort",
                "retry_count": 0,
            },
        ],
    },
    {
        "key": "bug_fix_flow",
        "name": "Bug 修复流程",
        "description": "复现→定位→修复→验证→关闭，标准 Bug 修复工作流。",
        "category": "development",
        "steps": [
            {
                "step_key": "reproduce",
                "name": "问题复现",
                "order": 0,
                "depends_on": [],
                "required_capabilities": ["testing", "research"],
                "on_failure": "abort",
                "retry_count": 1,
            },
            {
                "step_key": "fix",
                "name": "修复实现",
                "order": 1,
                "depends_on": ["reproduce"],
                "required_capabilities": ["frontend", "backend"],
                "on_failure": "abort",
                "retry_count": 0,
            },
            {
                "step_key": "verify",
                "name": "验证修复",
                "order": 2,
                "depends_on": ["fix"],
                "required_capabilities": ["testing"],
                "on_failure": "abort",
                "retry_count": 1,
            },
            {
                "step_key": "close",
                "name": "关闭问题",
                "order": 3,
                "depends_on": ["verify"],
                "required_capabilities": ["coordination"],
                "on_failure": "skip",
                "retry_count": 0,
            },
        ],
    },
    {
        "key": "daily_standup",
        "name": "每日站会汇总",
        "description": "收集各 Agent 的运行状态和阻塞项，生成每日报告。适合定时触发（Cron）。",
        "category": "coordination",
        "steps": [
            {
                "step_key": "collect_status",
                "name": "收集 Agent 状态",
                "order": 0,
                "depends_on": [],
                "required_capabilities": ["coordination"],
                "on_failure": "continue",
                "retry_count": 0,
            },
            {
                "step_key": "generate_report",
                "name": "生成站会报告",
                "order": 1,
                "depends_on": ["collect_status"],
                "required_capabilities": ["documentation"],
                "on_failure": "continue",
                "retry_count": 0,
            },
        ],
    },
]
